### ISSUE TITLE
User activity data export

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/newspaper-curation-app#126]
Create a spreadsheet/CSV download of user actions in NCA for filtering/sorting on actions in a local application (Excel, etc.)

The download could be customized with selected time period.

**Comment by jechols** [comment]
This has had two asks now, so it's probably worth getting some time, even if the initial implementation is just a simple tab- or comma-separated list of raw data much like mysql would return from a query like this:

```sql
  SELECT `when`, user, action
    FROM audit_logs
    WHERE
      action <> 'autosave' AND
      `when` >= '<insert date here>'
    ORDER BY user, `when`;
```

**Comment by jechols** [comment]
The raw SQL reports time in UTC - I don't recall why I saved it that way other than it probably seemed more portable.  When building a web-enabled export, I'll want to translate that to local server time.

**Comment by jechols** [comment]
For many actions, the message should probably also be put in the CSV.  Some actions store way too much useless information, like the full HTTP POST, but many have useful info like the issue id, and that would probably be useful to see.  And since you can hide what you want in Excel, more information is probably better than less.

**Comment by sseymore** [comment]
Just adding a comment that if this functionality could be built out into a dashboard-like interface for viewing user activity in NCA, that would also be great.
