### ISSUE TITLE
Fix docs for developer setup

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/newspaper-curation-app#164]
Docs suggest devs can build the binaries outside of docker and mount them in. This works probably 80% of the time... and is a terrible idea because of that other 20%. We need documentation for either 100% in-container dev or else a hybrid option where the Go parts are 100% local and db/iiif are containerized (e.g., via `scrips/localdev.sh`).

I'm leaning toward the latter. Despite it being pretty weird, it's what I actually do for most dev since it's a lot faster to make changes and just rebuild it locally.

If we don't want to deal with a major doc rewrite, one option we could consider is just making it extremely clear that you have to alter the Dockerfile to match your OS if you compile locally. That omission is inexcusable....

**Comment by techgique** [comment]
Building binaries externally and having to mount them in definitely threw me for a loop. It makes sense for NCA development workflow though. I don't think we can really ever get NCA / Scoop to a zero config status since it needs at least an ONI / chronam site to retrieve issue data from at boot, but using the Go binaries built by the nca_web Docker image by default seems much simpler. I suggest we do that out of the box and have documentation with the OS compatibility warning for how to mount externally built binaries in the Docker Compose override example file

**Comment by jechols** [comment]
Closing this - the official docs were updated to say you *can* use docker for the whole stack, but you really should just run NCA locally, and connect to docker for things like sftpgo, mariadb, etc.
