### ISSUE TITLE
Figure out a way to show page count for each issue

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/newspaper-curation-app#67]
Show page count for each issue, preferably in the Find Issues tab and if possible in the SFTP (Uploaded Issues) tab, too. In the SFTP tab, there are often pdf issues and single page pdfs so there would need to be a way to do a combined page count.

**Comment by jechols** [comment]
For the Find Issues tool, this should be possible.  I can look into it.  It shouldn't be more than a day of work I think.  But that's only for the issues which NCA has already processed in some way.

For uploads, it's a more difficult problem.  I'll have to look into this.  Since uploads are not yet in the system, NCA hasn't done any processing to them.  We don't want to add processing until we're sure we want them added to NCA in the first place, because once they're in the system, they're a lot harder to manually fix when there are things like two issues uploaded in a single folder.

It's possible we could do a count on the fly for these, but it might be way too slow.  I'm not sure.  If it's like 10 seconds per issue and you look at an uploads folder with 50 issues, that's obviously a deal-breaker.  But it's possible we could do something fancy.  Like... when an upload has been sitting long enough (48 hours is generally our safe time period), NCA could consider it ready for processing and actually run its normal processes but toss things into a temporary workspace so that if we don't queue the issue, it isn't something we have to yank out of the database.  And then if we *do* queue the issue, it's already been processed.  It would take some work to make something like this happen, but it might be handy.

**Comment by sseymore** [comment]
I just want to comment that if this could be done in the next 4 weeks off, that would be great! Not sure if we want to add a high priority label.

**Comment by jechols** [comment]
I would need more information for this - as I said in my first comment, it's doable in some contexts, but it may be impractical in others without some preliminary work.  If you want this to happen in all cases, the preliminary work would probably be two to five days on its own.

**Comment by jechols** [comment]
I'm starting this, as it'll help out with #220, but I'm not going to try and show a page count for anything that hasn't at least hit the curation step. Too much work to do it right, and potentially a lot of risk in pre-processing uploads that then have to be put into a new "not queued but partially processed" state.
