### ISSUE TITLE
Implement SFTP-like upload web form

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/newspaper-curation-app#71]
This may be a pipe dream.  Let's just get that out of the way.

Problem
---

Some publishers can't automate uploads via sftp, so they have to do everything manually using an sftp client like Filezilla.  This is cumbersome for them as well as difficult for us to support.  Basically if they aren't already familiar with sftp, we need to train them.  If they are already familiar, they probably have it automated.

Those who aren't familiar are doing this very manually, which can lead to a whole slew of errors: uploads going to the top-level folder instead of being put into a date folder, incorrect name conventions for folders, or even uploads that include lots of non-PDF files which end up having to be deleted before we process the issue.

Solution?
---

A web form that replaces all the manual folder-naming would be ideal.  It won't be easy to make this work well, but here's a general outline.

- We have a totally separate web server running on a public server
  - The internal NCA workflow app won't keep living on a public web server forever, so a separate app is a must
  - Code repo doesn't change: it's just a new binary, and might even share some of the code
  - Having a separate app means: we don't have to complicate NCA by having publisher logins living alongside internal SSO logins, we don't have to worry about what's exposed by accident, etc.
  - If it's too cumbersome to put the new system on its own host, we can still just run it locally and have something proxy a different hostname or even URL to the new app.  This means we can still lock down the workflow app to library-only users.
- The publishers' credentials can be exported to the public server or else read from the database
- A publisher logs in and is given a very simple uploader with the minimal data we require
  - We could expand this to ask them for a lot of metadata if we wanted, I'm not sure what we'd prefer
- We could do a quick preflight-style check on the PDF to make sure we can read and process it, giving the publisher immediate information about problems that prevent it from being usable (say they upload an illustrator file that was accidentally renamed to PDF).
- On success, we *might* be able to just dump the issue straight into the workflow instead of having to wait for somebody to log into the workflow app and queue it up.

**Comment by raybrarian** [comment]
Hey @jechols! Please prioritize this one for NCA going forward - thanks!

**Comment by sseymore** [comment]
On success, we might be able to just dump the issue **straight into the workflow** instead of having to wait for somebody to log into the workflow app and queue it up.

^^Also, skipping the page review step, which just renumbers the pages, would be great. Having a batch renumbering tool that is queued when the issue moves out of SFTP to NCA would help so much.

**Comment by sseymore** [comment]
Adding more comments for context and requested suggestions from publishers:

- For the "web form": This sounds like a single-PDF upload interface only. This is great, but also a lot of publishers create the directories/files locally and then upload to FileZlla in batch, usually by drag and drop, with the PDF(s) already inside the folder/subdirectory because it's easier to create folders and move files locally than in FileZilla.
- Having an interface in their directories that allows for drag and drop, similar to Google Drive or Dropbox.
- Icons (like in SFTPGo) for uploading, renaming, and deletion instead of right-clicking for these actions in FileZilla. 
-Boosting my comment above again. If the issue passes QA, it should go directly into workflow on NCA without page renumbering since QA is checking for page ordering. The page renumbering step is unnecessary since we don't even have page numbering conventions (just sequential) for the in-house scans.

**Comment by sseymore** [comment]
Re-asking a question for later discussion: Are there other solutions out there besides FileZilla, WinSCP, and SFTPGo that could address some of these needs?

**Comment by jechols** [comment]
> Re-asking a question for later discussion: Are there other solutions out there besides FileZilla, WinSCP, and SFTPGo that could address some of these needs?

Any application which does sftp would work, and you can do a quick search for "sftp client" to get a lot of options, but I'm not sure I can suggest "good" ones. I think somebody would need to do a deeper dive, installing and playing with various apps to see what's useful / helpful.... I wonder if DJ might have some thoughts.

It's also possible we could look into WebDAV, which I've heard in the past is very finicky but lets a person "mount" an sftp service as if it were a local file system. The support side of this could be monstrous, however, as problems could require a lot of technical understanding to try and get past. This might be worth asking DJ about as well, since it would likely be his problem to support the ODNP staff while they're trying to remotely support publishers...

**Comment by raybrarian** [comment]
sftp.net has a bunch of options: [https://www.sftp.net/clients](https://www.sftp.net/clients) some might be easier than others, but they will all probably not have this feature set. I think we might be better off paying for a cloud service, if that is a possibility. There are several, I think they all charge per credential: [https://sftptogo.com/pricing](https://sftptogo.com/pricing)

**Comment by jechols** [comment]
If I'm reading it right, sftptogo would be a server, not a client. As such, we'd have to remove SFTPGo and then redesign NCA to make use of it.

I don't know that they have a client app that would improve our publishers' experience.

**Comment by jechols** [comment]
This ticket has gone crazy, the branch is five years old, and the work in progress was determined not to meet the needs of the stakeholder (Sarah Beth) who had been seeing this as a full replacement for Filezilla. Unfortunately that is infeasible, and this ticket was mostly dropped once we found that out, we just forgot to update it.

Closing the ticket - this may be something to revisit one day, but not during the Scoop grant, and we'd probably be better served improving the SFTPGo interface (and using its hooks to validate uploads) rather than implementing a fully custom sftp client.
